//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapanCrossWord_Yakovlev_k0210.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JapanCrossWord_Yakovlev_k0210.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щелчками левой кнопки мыши вы закрашиваете выделенное поле (квадратик).
        ///Щелчками правой кнопки мыши можно пометить пустующее поле, т.е. выводится крестик.
        ///Двойным щелчком мыши можно удалить и цвет, и крестик.
        ///Клетки с заданием изначально имеют белый цвет шрифта. По мере отгадывания кроссворда пользователь может щелчком мыши вычеркнуть цифры в разгаданных строчках и/или столбиках..
        /// </summary>
        internal static string control {
            get {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap game1 {
            get {
                object obj = ResourceManager.GetObject("game1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap game2 {
            get {
                object obj = ResourceManager.GetObject("game2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap game3 {
            get {
                object obj = ResourceManager.GetObject("game3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap game4 {
            get {
                object obj = ResourceManager.GetObject("game4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00010000000111000000110100000011111000000011110000011111100001111111000011111101011111110111101111110.
        /// </summary>
        internal static string otv1 {
            get {
                return ResourceManager.GetString("otv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0100000000010011000000011001110000011101101111111011111011111011111111111111111111111111111111111011111101110010011100011001001100000110101100000001111100000.
        /// </summary>
        internal static string otv2 {
            get {
                return ResourceManager.GetString("otv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00011011000100010100011100101001111100100111111101011110111111111000111111100011111111101111010111101100100110001000001000.
        /// </summary>
        internal static string otv3 {
            get {
                return ResourceManager.GetString("otv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0010101000001010100000000000000111111100011011111101101111010111111110011111110010111110010111111110.
        /// </summary>
        internal static string otv4 {
            get {
                return ResourceManager.GetString("otv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic {
            get {
                object obj = ResourceManager.GetObject("pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Японский кроссворд представляет собой зашифрованный рисунок, в котором цифры слева от рядов и сверху над колонками показывают, сколько групп закрашенных клеток находится в соответствующей линии и сколько закрашенных клеток содержит каждая группа. Например, три числа - 2, 5, 9 - обозначают, что в этом ряду есть три группы, состоящие: первая - из двух, вторая - из пяти, третья - из девяти слитных закрашенных клеток.
        ///2) Группы разделены, по крайней мере, одной пустой клеткой.
        ///3) Группы не всегда начинаютс [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pravila {
            get {
                return ResourceManager.GetString("Pravila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000001000000030000020100000005000000040000000600000007000006010000070100000306.
        /// </summary>
        internal static string stolb1 {
            get {
                return ResourceManager.GetString("stolb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000010100000202000003030002070200030503000000130000001300000606000301030002010200020102000000050.
        /// </summary>
        internal static string stolb2 {
            get {
                return ResourceManager.GetString("stolb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000020201010101020101020003010300040104000000090000000700000009000401040002010200000101.
        /// </summary>
        internal static string stolb3 {
            get {
                return ResourceManager.GetString("stolb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00010101000101010000000000000007000002060002040100000008000000070001050100000008.
        /// </summary>
        internal static string stolb4 {
            get {
                return ResourceManager.GetString("stolb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000300000000000000000202010000000000000001020709070605040103.
        /// </summary>
        internal static string strok1 {
            get {
                return ResourceManager.GetString("strok1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000000202050504050502020000050906060201040102060609050.
        /// </summary>
        internal static string strok2 {
            get {
                return ResourceManager.GetString("strok2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000000000000000004040001030003010004040103080503070305080301.
        /// </summary>
        internal static string strok3 {
            get {
                return ResourceManager.GetString("strok3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000000000001000005020102000205010201010704070707010101.
        /// </summary>
        internal static string strok4 {
            get {
                return ResourceManager.GetString("strok4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zero {
            get {
                object obj = ResourceManager.GetObject("zero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
